# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb7ccab2c2c32aee9d4ae955ba9c32896cd825078d95f035e146ae53622f5ec2c70eed91743c0504d42c59614e33e8296462365106b557964444873dc77d2bae

test:
  secret_key_base: 4d3515fd346cb68a0644ad8de1d0e31b320531847957eefc194beebfddb52b1bed497380a2dff7a6c8fa7cb883f661dcb7a12e2c7d53c0dcc9a8fa29fe0dffde

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
